# Generated by Django 6.0.2 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom",
            name="image",
            field=models.ImageField(
                default="showroomAdmin/user-profile", upload_to="showroomAdmin/"
            ),
        ),
    ]
