# Generated by Django 6.0.2 on 2026-02-23 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom",
            name="pincode",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$", "Enter a valid 6-digit pincode"
                    )
                ],
            ),
        ),
    ]
