# Generated by Django 6.0.2 on 2026-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0002_showroom_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="showroom",
            name="primary_color",
            field=models.CharField(default="#2563eb", max_length=10),
        ),
    ]
