# Generated by Django 6.0.2 on 2026-04-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_showroom_primary_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showroom",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
