# Generated by Django 6.0.2 on 2026-03-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "deal_id",
                    models.CharField(
                        editable=False, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("profit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deal_date", models.DateField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        db_column="customer_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "db_table": "deal",
            },
        ),
    ]
