# Generated by Django 6.0.2 on 2026-03-13 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deal", "0001_initial"),
        ("vehicle", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="showroom_id",
            field=models.ForeignKey(
                db_column="showroom_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="vehicle_id",
            field=models.ForeignKey(
                db_column="vehicle_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicle.vehicle",
            ),
        ),
    ]
