# Generated by Django 6.0.2 on 2026-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
