# Generated by Django 6.0.2 on 2026-03-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name_name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
