# Generated by Django 6.0.2 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_first_name_customer_last_name_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                default="customer/user-profile", upload_to="customer/"
            ),
        ),
    ]
