# Generated by Django 6.0.2 on 2026-03-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Credit/Debit Card"),
                            ("UPI", "UPI"),
                            ("NET", "Net Banking"),
                            ("WALLET", "Wallet"),
                            ("COD", "Cash on Delivery"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="deal.deal",
                    ),
                ),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
