# Generated by Django 6.0.2 on 2026-03-13 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("variant", models.CharField(max_length=100)),
                ("manufacturing_year", models.PositiveIntegerField()),
                ("fuel_type", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("km_driven", models.PositiveIntegerField()),
                ("registration_no", models.CharField(max_length=10, unique=True)),
                ("chasis_no", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(max_length=20)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("purchase_date", models.DateField()),
                (
                    "vehicle_status",
                    models.CharField(
                        choices=[
                            ("avail", "Available"),
                            ("sold", "Sold"),
                            ("reser", "Reserved"),
                        ],
                        default="Avail",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "showroom_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vehicle",
                "ordering": ["-created_at"],
            },
        ),
    ]
