# Generated by Django 6.0.2 on 2026-03-18 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_status",
            field=models.CharField(
                choices=[
                    ("Avail", "Available"),
                    ("sold", "Sold"),
                    ("reser", "Reserved"),
                ],
                default="Avail",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="vehicle_images/")),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_images",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
