# Generated by Django 6.0.2 on 2026-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0002_alter_vehicle_vehicle_status_vehicleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="registration_no",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
