# Generated by Django 6.0.2 on 2026-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_vehicle_selling_price_alter_vehicle_registration_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="mileage",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
