# Generated by Django 6.0.2 on 2026-03-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0004_vehicle_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
