# Generated by Django for dealTrack

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_new_showroom_registration', models.BooleanField(default=True, help_text='Allow new users to register as showrooms')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put the platform in maintenance mode')),
                ('platform_announcement', models.TextField(blank=True, help_text='Announcement message to display to all users', null=True)),
                ('max_showrooms_per_user', models.IntegerField(default=1, help_text='Maximum number of showrooms a user can create')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
                'db_table': 'admin_settings',
            },
        ),
    ]
