# Generated by Django 6.0.2 on 2026-03-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("repair", "Repair"),
                            ("service", "Service"),
                            ("rto", "RTO"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True, null=True)),
                ("expense_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "expense",
            },
        ),
    ]
